docker_scripts/ubuntu-20.04-gnu_10-eigen_3.3.7-gtest-trilinos_hash-ef73d14babf6e7556b0420add98cce257ccaa56b.dockerfile

- added python3 to installed packages on docker image with trilinos
- build docker image
- pushed docker image to the repository
Closes #350

#350: CI: docker images missing python

---

include/pressio/ops/eigen/ops_elementwise_multiply.hpp
include/pressio/ops/eigen/ops_level2.hpp
include/pressio/ops/eigen/ops_level3.hpp
include/pressio/ops/epetra/ops_elementwise_multiply.hpp
include/pressio/ops/epetra/ops_level2.hpp
include/pressio/ops/epetra/ops_level3.hpp
include/pressio/ops/tpetra/ops_level2.hpp
include/pressio/ops/tpetra/ops_level3.hpp
tests/functional_small/ops/ops_eigen_level2.cc
tests/functional_small/ops/ops_eigen_level3.cc
tests/functional_small/ops/ops_eigen_vector.cc
tests/functional_small/ops/ops_epetra_level2.cc
tests/functional_small/ops/ops_epetra_level3.cc
tests/functional_small/ops/ops_epetra_vector.cc
tests/functional_small/ops/ops_kokkos_level2.cc
tests/functional_small/ops/ops_kokkos_level3.cc
tests/functional_small/ops/ops_kokkos_vector.cc
tests/functional_small/ops/ops_tpetra_block_level2.cc
tests/functional_small/ops/ops_tpetra_block_level3.cc
tests/functional_small/ops/ops_tpetra_block_vector.cc
tests/functional_small/ops/ops_tpetra_level2.cc
tests/functional_small/ops/ops_tpetra_level3.cc
tests/functional_small/ops/ops_tpetra_vector.cc

This PR fixes `NaN` injection bug (detected on https://github.com/Pressio/pressio/pull/337#issuecomment-1057999321) in `pressio::ops::product()` and `pressio::ops::elementwise_multiply()` (no other ops seem to be affected).
With the bug in place we'll get `NaN` instead of expected results when output variable is initialized with `NaN` and `beta=0` is set for the operation, e.g. `y = alpha * x * z + beta * y` with `beta=0` and `y=NaN`. The solution proposed here is to skip the update alltogether if `beta==0`.
Tests for these ops are expanded to cover both `beta==0` and `beta!=0` execution paths, with the first one setting `NaN` in the result variable to simulate it's uninitialized state.

Fix `NaN` injection bug in `pressio::ops`

---

include/pressio/type_traits/nested_typedef_detection.hpp
tests/functional_small/type_traits/detect_typedefs.cc

This PR removes unused `has_*_typedef` detection predicates and supplies the missing ones in the unit test.

Review `typedef` detection predicates

---

tests/functional_small/ode_steppers/ode_all_explicit_schemes_fixed_mass_matrix_correctness_eigen.cc
tests/functional_small/ode_steppers/ode_all_explicit_schemes_varying_mass_matrix_correctness_eigen.cc
tests/functional_small/ode_steppers/ode_bdf1_simple_correctness_eigen.cc
tests/functional_small/ode_steppers/ode_bdf2_simple_correctness_eigen.cc
tests/functional_small/ode_steppers/ode_rk4_custom_ind_var_type_eigen.cc
tests/functional_small/ode_steppers/ode_rk4_simple_correctness_eigen.cc
tests/functional_small/ops/ops_epetra_vector.cc
tests/functional_small/ops/ops_tpetra_block_vector.cc
tests/functional_small/ops/ops_tpetra_vector.cc
tests/functional_small/rom/lspg_steady/main1.cc
tests/functional_small/rom/lspg_steady/main2.cc
tests/functional_small/rom/lspg_steady/main3.cc
tests/functional_small/rom/lspg_steady/main4.cc
tests/functional_small/rom/lspg_unsteady/main1.cc
tests/functional_small/rom/lspg_unsteady/main4.cc
tests/functional_small/solvers_nonlinear/operators.cc

This PR replaces exact `EXPECT_DOUBLE_EQ` comparisons with tolerance-based `EXPECT_NEAR`.
Fixes #437
> **Note:** Baseline tolerance picked at `1e-15: to be adjusted where hinted by failing tests.

tests: fix floating point comparisons

---

docs/source/components/rom_linear_subspace.rst

This PR updates `LinearSubspace` constraints according to https://github.com/Pressio/pressio/issues/440#issuecomment-1293062547.
Fixes #440

docs: rom: update `LinearSubspace` constraints

---

include/pressio/expressions/impl/diag_classes.hpp
include/pressio/expressions/impl/span_classes.hpp
include/pressio/expressions/impl/subspan_classes.hpp

Fixing a typo we found with @fnrizzi based on `nvcc` 11.8 error:
```
/pressio/include/pressio/././mpl/enable_if_t.hpp(60): error: class "std::enable_if<false, double &>" has no member "type"
detected during:
instantiation of type "pressio::mpl::enable_if_t<false, double &>" 
/pressio/include/pressio/././expressions/impl/span_classes.hpp(210): here
instantiation of class "pressio::expressions::impl::SpanExpr<VectorType, pressio::mpl::enable_if_t<pressio::is_vector_kokkos<VectorType, void>::value, void>> [with VectorType=Kokkos::View<double *>]" 
/pressio/include/pressio/././expressions/span.hpp(77): here
instantiation of "auto pressio::span(T &, std::size_t, std::size_t) [with T=Kokkos::View<double *>]" 
/pressio/tests/functional_small/ops/ops_kokkos_level2.cc(82): here …
```

expressions: fix templating typo

---

include/pressio/ops.hpp
include/pressio/ops/teuchos/ops_extent.hpp
include/pressio/ops/teuchos/ops_fill.hpp
include/pressio/ops/teuchos/ops_scale.hpp
include/pressio/ops/teuchos/ops_set_zero.hpp

@fnrizzi 
This PR implements missing level1 ops for `Teuchos::SerialDenseVector<Index, Scalar>`:
* `extent()`
* `fill()`
* `set_zero()`
* `scale()`

ops: teuchos: implement missing level1 ops

---

include/pressio/ops/kokkos/ops_level3.hpp
tests/functional_small/ops/ops_kokkos_level3.cc

@fnrizzi 
refs #451
* Done:
* Todo - for discussion:
For `C = alpha * op(A) * op(B) + beta * C` there are following level-3 `pressio::ops::product()` implementations working on Kokkos objects:
| `A` | `B` | `C` | op(A) | op(B) |
|:---:|:---:|:---:|:---:|:---:|
| kokkos matrix | kokkos matrix | kokkos matrix | `nontranspose` | `nontranspose` |
| kokkos matrix | kokkos matrix | kokkos matrix | `transpose` | `nontranspose` |
| kokkos matrix | ⨯<br> (self&nbsp;product) | kokkos matrix | `transpose` | `nontranspose` |
| kokkos matrix | ⨯<br> (self&nbsp;product) | auto<br>(returned value) | `transpose` | `nontranspose` |
Test cases for Kokkos level-3 implementations of `pressio::ops::product()` (op(B) is always `nontranspose`):
| test | `A` | `B` | `C` | op(A) |
|:---|:---|:---|:---|:---:|
| …

ops: kokkos: revise matrix-matrix product

---

include/pressio/ops/eigen/ops_level3.hpp
tests/functional_small/ops/ops_eigen_level3.cc

@fnrizzi 
refs #451
* Done:
* Todo - for discussion:
For `C = alpha * op(A) * op(B) + beta * C` there are following level-3 `pressio::ops::product()` implementations working on Eigen objects:
| `A` | `B` | `C` | op(A) | op(B) | remarks |
|:---:|:---:|:---:|:---:|:---:|:---|
| eigen matrix | eigen matrix | eigen matrix | `transpose` | `nontranspose` | |
| eigen matrix | eigen matrix | eigen matrix | `nontranspose` | `nontranspose` | |
| eigen matrix | ⨯<br> (self&nbsp;product) | eigen matrix | `transpose` | `nontranspose` | + value returning overload |
| eigen `as_diagonal_matrix` | eigen matrix | eigen matrix | `nontranspose` | `nontranspose` | |
Test cases for Eigen level-3 implementations of `pressio::ops::product()` (op(B) is always `nontranspose`):
| test | `A` | `B` | `C` | op(A) | …

ops: eigen: revise matrix-matrix product

---

include/pressio/ops/tpetra/ops_level3.hpp
tests/functional_small/ops/ops_tpetra_level3.cc

@fnrizzi 
refs #451
Contents
Tpetra level-3 `pressio::ops::product()` (i.e. performing `C = alpha * op(A) * op(B) + beta * C`) overloads:
| `A` | `B` | `C` | op(A) | op(B) |
|:---:|:---:|:---:|:---:|:---:|
| tpetra MV | tpetra MV | eigen col-major matrix | `transpose` | `nontranspose` |
| tpetra MV | tpetra MV | dynamic&nbsp;eigen&nbsp;matrix<br> (returned&nbsp;value) | `transpose` | `nontranspose` |
| tpetra MV | ⨯<br> (self&nbsp;product) | eigen matrix | `transpose` | `nontranspose` |
| tpetra MV | ⨯<br> (self&nbsp;product) | dynamic&nbsp;eigen&nbsp;matrix<br> (returned&nbsp;value) | `transpose` | `nontranspose` |
| tpetra MV | ⨯<br> (self&nbsp;product) | kokkos&nbsp;dense&nbsp;matrix | `transpose` | `nontranspose` |
| tpetra MV | ⨯<br> (self&nbsp;product) | …

ops: tpetra: revise matrix-matrix product

---

include/pressio/ops/epetra/ops_level3.hpp
tests/functional_small/ops/ops_epetra_level3.cc

@fnrizzi
refs #451
Contents
Epetra level-3 `pressio::ops::product()` (i.e. performing `C = alpha * op(A) * op(B) + beta * C`) overloads:
| `A` | `B` | `C` | op(A) | op(B) |
|:---:|:---:|:---:|:---:|:---:|
| epetra MV | epetra MV | eigen matrix | `transpose` | `nontranspose` |
| epetra MV | epetra MV | dynamic&nbsp;eigen&nbsp;matrix<br> (returned&nbsp;value) | `transpose` | `nontranspose` |
| epetra MV | ⨯<br> (self&nbsp;product) | eigen matrix | `transpose` | `nontranspose` |
| epetra MV | ⨯<br> (self&nbsp;product) | dynamic&nbsp;eigen&nbsp;matrix<br> (returned&nbsp;value) | `transpose` | `nontranspose` |
Test cases for Epetra level-3 implementations of `pressio::ops::product()` (op(A) is always `transpose` and op(B) is always `nontranspose`):
| test | `A` | `B` | `C` | …

 ops: epetra: revise matrix-matrix product

---

include/pressio/ops/tpetra_block/ops_level3.hpp
tests/functional_small/ops/fixtures/tpetra_block_only_fixtures.hpp
tests/functional_small/ops/ops_tpetra_block_level3.cc

@fnrizzi 
refs #451
Contents
Tpetra-block level-3 `pressio::ops::product()` (i.e. performing `C = alpha * op(A) * op(B) + beta * C`) overloads:
| `A` | `B` | `C` | op(A) | op(B) |
|:---:|:---:|:---:|:---:|:---:|
| tpetra MV-block | tpetra MV-block | eigen col-major matrix | `transpose` | `nontranspose` |
| tpetra MV-block | tpetra MV-block | dynamic&nbsp;eigen&nbsp;matrix<br> (returned&nbsp;value) | `transpose` | `nontranspose` |
| tpetra MV-block | ⨯<br> (self&nbsp;product) | eigen matrix | `transpose` | `nontranspose` |
| tpetra MV-block | ⨯<br> (self&nbsp;product) | dynamic&nbsp;eigen&nbsp;matrix<br> (returned&nbsp;value) | `transpose` | `nontranspose` |
| tpetra MV-block | ⨯<br> (self&nbsp;product) | kokkos&nbsp;dense&nbsp;matrix | `transpose` | `nontranspose` |
| tpetra MV-block | …

ops: tpetra-block: revise matrix-matrix product

---

include/pressio/ops/epetra/ops_rank1_update.hpp
tests/functional_small/ops/ops_epetra_vector.cc

 ops: epetra: revise rank-1 update

---

tests/functional_small/ops/ops_eigen_vector.cc

ops: eigen: cover all NaN execution paths of rank-1 update in unit tests

---

include/pressio/ops/kokkos/ops_vector_update.hpp
include/pressio/ops/kokkos/ops_vector_update_kokkos_functors.hpp
tests/functional_small/ops/ops_kokkos_vector.cc

 ops: kokkos: revise rank-1 update

---

include/pressio/ops.hpp
include/pressio/ops/kokkos/ops_rank2_update.hpp
tests/functional_small/ops/ops_kokkos_matrix.cc

ops: kokkos: revise rank-2 `update`

---

include/pressio/ops/eigen/ops_rank2_update.hpp

Follows #543: for some reason GitHub refused to acknowledge f80b6fb4eac43dd948a8456c7c6279e74eebf31d as part of [PR#543](https://github.com/Pressio/pressio/pull/543#discussion_r1086445807), so I'm posting it on a new PR
refs #449

ops: eigen: cast coefficients to `const` scalar type

---

include/pressio/ops/epetra/ops_multi_vector_update.hpp
tests/functional_small/ops/ops_epetra_multi_vector.cc

ops: epetra: revise rank-2 `update`

---

include/pressio/ops/tpetra/ops_multi_vector_update.hpp
tests/functional_small/ops/ops_tpetra_multi_vector.cc

ops: tpetra: revise rank-2 `update`

---

include/pressio/ops/tpetra_block/ops_multi_vector_update.hpp
tests/functional_small/ops/ops_tpetra_block_multi_vector.cc

ops: tpetra-block: revise rank-2 `update`

---

include/pressio/ops.hpp
include/pressio/ops/epetra/ops_min_max.hpp
tests/functional_small/ops/ops_epetra_multi_vector.cc
tests/functional_small/ops/ops_epetra_vector.cc

refs #447
Epetra overloads of `pressio::ops::min` and `pressio::ops::max`:
| `min`<br>`max` | Epetra vector or multi-vector | requires underlying scalar type to be known integral of floating-point type |
| `ops_epetra_vector.cc` | `ops_epetra.vector_min_max` | `Epetra_Vector` |
| `ops_epetra_multi_vector.cc` | `epetraMultiVectorGlobSize15Fixture.multi_vector_min_max` | `Epetra_MultiVector` |

ops: epetra: `min`/`max` implementation and tests

---

include/pressio/ops.hpp
include/pressio/ops/kokkos/ops_min_max.hpp
tests/functional_small/ops/ops_kokkos_diag.cc
tests/functional_small/ops/ops_kokkos_matrix.cc
tests/functional_small/ops/ops_kokkos_span.cc
tests/functional_small/ops/ops_kokkos_subspan.cc
tests/functional_small/ops/ops_kokkos_vector.cc

refs #447
Kokkos overloads of `pressio::ops::min` and `pressio::ops::max`:
|`min`<br>`max`|Kokkos view (rank-1 or rank-2)<br>or Kokkos expression| requires underlying scalar type to be known integral of floating-point type|
| `ops_kokkos_vector.cc` | `ops_kokkos.vector_min_max` | `Kokkos::View<double*>` |
| `ops_kokkos_matrix.cc` | `ops_kokkos.dense_matrix_min_max` | `Kokkos::View<double**>` |
| `ops_kokkos_diag.cc` | `ops_kokkos.diag_min_max` | `pressio::diag( Kokkos::View<double**> )` |
| `ops_kokkos_span.cc` | `ops_kokkos.span_min_max` | `pressio::span( Kokkos::View<double*> )` |
| `ops_kokkos_subspan.cc` | …

ops: kokkos: `min`/`max` implementation and tests

---

include/pressio/ops/teuchos/ops_scale.hpp
tests/functional_small/ops/CMakeLists.txt
tests/functional_small/ops/ops_teuchos_vector.cc

refs #445
Teuchos overloads of `pressio::ops::scale`:
| `scale` | Teuchos vector | requires underlying scalar type to be known integral of floating-point type |
|:---|:---:|:---:|
| `ops_teuchos_vector.cc` | `ops_teuchos.vector_scale` | `Teuchos::SerialDenseVector<int, double>` |

ops: teuchos: revise `scale`

---

include/pressio/ops/kokkos/ops_scale.hpp
tests/functional_small/ops/ops_kokkos_vector.cc

refs #445
Kokkos overloads of `pressio::ops::scale`:
|`scale`|Kokkos view (rank-1 or rank-2)<br>or Kokkos expression| requires underlying scalar type<br> to be known integral of floating-point type|
| `ops_kokkos_vector.cc` | `ops_kokkos.vector_scale` | `Kokkos::View<double*>` |
| `ops_kokkos_matrix.cc` | `ops_kokkos.dense_matrix_scale` | `Kokkos::View<double**>` |
| `ops_kokkos_diag.cc` | `ops_kokkos.diag_scale` | `pressio::diag( Kokkos::View<double**> )` |
| `ops_kokkos_span.cc` | `ops_kokkos.span_scale` | `pressio::span( Kokkos::View<double*> )` |
| `ops_kokkos_subspan.cc` | `ops_kokkos.subspan_scale` | `pressio::subspan( …

ops: kokkos: revise `scale`

---

include/pressio/ops/eigen/ops_norms.hpp

refs #450
Eigen overloads of norms:
| `norm1`<br>`norm2` | Eigen vector or rank-1 expression | requires underlying scalar type to be known integral of floating-point type |
| `ops_eigen_vector.cc` | `ops_eigen.vector_norm1`<br>`ops_eigen.vector_norm2` | `Eigen::VectorXd` |
| `ops_eigen_diag.cc` | `ops_eigen.diag_norms` | `pressio::diag( Eigen::MatrixXd )` |
| `ops_eigen_span.cc` | `ops_eigen.span_norms` | `pressio::span( Eigen::VectorXd )` |

ops: eigen: revise overload constraints of norms

---

include/pressio/ops/epetra/ops_norms.hpp

refs #450
Epetra overloads of norms:
| `norm1`<br>`norm2` | `Epetra_Vector` | requires underlying scalar type to be known integral of floating-point type |
| `ops_epetra_vector.cc` | `ops_epetra.vector_norm1`<br>`ops_epetra.vector_norm2` | `Epetra_Vector` |

ops: epetra: revise overload constraints of norms

---

include/pressio/ops/kokkos/ops_norms_vector.hpp

refs #450
Kokkos overloads of norms:
| `norm1`<br>`norm2` | rank-1 Kokkos view or expression | requires underlying scalar type to be known integral of floating-point type|
| `ops_kokkos_vector.cc` | `ops_kokkos.vector_norm1`<br>`ops_kokkos.vector_norm2` | `Kokkos::View<double*>` |
| `ops_kokkos_diag.cc` | `ops_kokkos.diag_norms` | `pressio::diag( Kokkos::View<double**> )` |
| `ops_kokkos_span.cc` | `ops_kokkos.span_norms` | `pressio::span( Kokkos::View<double*> )` |

 ops: kokkos: revise overload constraints of norms

---

include/pressio/ops/tpetra/ops_norms.hpp

refs #450
Tpetra overloads of norms:
| `norm1`<br>`norm2` | Tpetra vector | requires underlying scalar type to be known integral of floating-point type |
| `ops_tpetra_vector.cc` | `ops_tpetra.vector_norm1`<br>`ops_tpetra.vector_norm2` | `Tpetra::Vector<>` |

ops: tpetra: revise overload constraints of norms

---

include/pressio/ops/tpetra_block/ops_norms.hpp

refs #450
Block Tpetra overloads of norms:
| `norm1`<br>`norm2` | Tpetra block vector | requires underlying scalar type to be known integral of floating-point type |
| `ops_tpetra_block_vector.cc` | `ops_tpetra_block.vector_norm1`<br>`ops_tpetra_block.vector_norm2` | `Tpetra::BlockVector<>` |

ops: tpetra-block: revise `norm1` and `norm2`

---

include/pressio/ops.hpp
include/pressio/ops/kokkos/ops_min_max.hpp
include/pressio/ops/tpetra/ops_min_max.hpp
tests/functional_small/ops/ops_kokkos_diag.cc
tests/functional_small/ops/ops_kokkos_matrix.cc
tests/functional_small/ops/ops_kokkos_span.cc
tests/functional_small/ops/ops_kokkos_subspan.cc
tests/functional_small/ops/ops_kokkos_vector.cc
tests/functional_small/ops/ops_tpetra_multi_vector.cc
tests/functional_small/ops/ops_tpetra_vector.cc

refs #447
Tpetra overloads of `pressio::ops::min` and `pressio::ops::max`:
| `min`<br>`max` | Tpetra vector or multi-vector | requires underlying scalar type to be known integral of floating-point type |
| `ops_tpetra_vector.cc` | `ops_tpetra.vector_min_max` | `Tpetra::Vector<>` |
| `ops_tpetra_multi_vector.cc` | `tpetraMultiVectorGlobSize15Fixture.multi_vector_min_max` | `Tpetra::MultiVector<>` |

ops: tpetra: `min`/`max` implementation and tests

---

include/pressio/ops.hpp
include/pressio/ops/tpetra_block/ops_min_max.hpp
tests/functional_small/ops/fixtures/tpetra_block_only_fixtures.hpp
tests/functional_small/ops/ops_tpetra_block_multi_vector.cc
tests/functional_small/ops/ops_tpetra_block_vector.cc

refs #447
Block Tpetra overloads of `pressio::ops::min` and `pressio::ops::max`:
| `min`<br>`max` | Tpetra block vector or multi-vector | requires underlying scalar type to be known integral of floating-point type |
| `ops_tpetra_vector.cc` | `ops_tpetra_block.vector_min_max` | `Tpetra::BlockVector<>` |
| `ops_tpetra_multi_vector.cc` | `tpetraBlockMultiVectorGlobSize15NVec3BlockSize4Fixture.multi_vector_min_max` | `Tpetra::BlockMultiVector<>` |

ops: tpetra-block: `min`/`max` implementation and tests

---

include/pressio/ops/tpetra_block/ops_extent.hpp

refs #522
Block Tpetra `extent` overloads:
|:---:|:---:|
| `extent(const T & objectIn, const IndexType i)` | Tpetra block vector |
| `extent(const T & objectIn, const IndexType i)` | Tpetra block multi-vector |
| `ops_tpetra_block_vector.cc` | `ops_tpetra_block.vector_extent` | `Tpetra::Vector<>` |
| `ops_tpetra_block_multi_vector.cc` | `tpetraBlockMultiVectorGlobSize15NVec3BlockSize4Fixture.multi_vector_extent` | `Tpetra::MultiVector<>` |

ops: tpetra-block: revise `extent` overload constraints

---

include/pressio/ops/eigen/ops_extent.hpp
tests/functional_small/ops/ops_eigen_vector.cc

refs #522
Eigen `extent` overloads:
| function | input |
|:---:|:---:|
| `extent(const T & objectIn, const IndexType i)` | native Eigen vector |
| `extent(const T & objectIn, const IndexType i)` | native Eigen matrix (dense or sparse) |
| `extent(const T & objectIn, const IndexType i)` | Eigen expression |
| `ops_eigen_vector.cc` | `ops_eigen.vector_extent` | `Eigen::VectorXd` |
| `ops_eigen_diag.cc` | `ops_eigen.diag_extent` | `pressio::diag( Eigen::MatrixXd )` |
| `ops_eigen_span.cc` | `ops_eigen.span_extent` | `pressio::span( Eigen::VectorXd )` |
| `ops_eigen_matrix.cc` | `ops_eigen.dense_matrix_extent` | `Eigen::MatrixXd` |
| `ops_eigen_subspan.cc` | `ops_eigen.subspan_extent` | …

ops: eigen: revise `extent`

---

include/pressio/ops.hpp
include/pressio/ops/teuchos/ops_norms.hpp
tests/functional_small/ops/ops_teuchos_vector.cc

refs #450
Teuchos overloads of norms:
| `norm1`<br>`norm2` | `Teuchos::SerialDenseVector<OrdinalType, ScalarType>` | requires underlying scalar type<br> to be known integral of floating-point type |
| `ops_teuchos_vector.cc` | `ops_teuchos.vector_norms` | `Teuchos::SerialDenseVector<int, double>` |

ops: teuchos: add norms implementation and unit test

---

include/pressio/ops/epetra/ops_deep_copy.hpp

refs #518
Epetra `deep_copy` overloads:
| function | input |
|:---:|:---:|
| `deep_copy( T2 & dest, const T1 & src )` | Epetra vectors or multi-vectors |
| `ops_epetra_vector.cc` | `ops_epetra.vector_deep_copy` | `Epetra_Vector` |
| `ops_epetra_multi_vector.cc` | `epetraMultiVectorGlobSize15Fixture.multi_vector_deep_copy` | `Epetra_MultiVector` |

ops: epetra: revise `deep_copy`

---

include/pressio/ops.hpp
include/pressio/ops/teuchos/ops_clone.hpp
tests/functional_small/ops/ops_teuchos_vector.cc

refs #517
Teuchos `clone` overloads:
| function | input `T` |
|:---:|:---:|
| `clone( T )` | `Teuchos::SerialDenseVector<OrdinalType, ScalarType>` |
| `ops_teuchos_vector.cc` | `ops_teuchos.vector_clone` | `Teuchos::SerialDenseVector<int, double>` |

ops: teuchos: add `clone` implementation and unit test

---

include/pressio/ops/tpetra_block/ops_clone.hpp

refs #517
Block Tpetra `clone` overloads:
| function | input `T` |
|:---:|:---:|
| `clone( T )` | Tpetra block vector or block multi-vector |
| `ops_tpetra_block_vector.cc` | `ops_tpetra_block.vector_clone` | `Tpetra::BlockVector<>` |
| `ops_tpetra_block_multi_vector.cc` | `tpetraBlockMultiVectorGlobSize15NVec3BlockSize4Fixture.multi_vector_clone` | `Tpetra::BlockMultiVector<>` |

ops: tpetra-block: revise `clone` overload constraints

---

include/pressio/ops/tpetra/ops_clone.hpp

refs #517
Tpetra `clone` overloads:
| function | input `T` |
|:---:|:---:|
| `clone( T )` | Tpetra vector or multi-vector |
| `ops_tpetra_vector.cc` | `ops_tpetra.vector_clone` | `Tpetra::Vector<>` |
| `ops_tpetra_multi_vector.cc` | `tpetraMultiVectorGlobSize15Fixture.multi_vector_clone` | `Tpetra::MultiVector<>` |

ops: tpetra: revise `clone` overload constraints

---

include/pressio/ops/epetra/ops_clone.hpp

refs #517
Epetra `clone` overloads:
| function | input `T` |
|:---:|:---:|
| `clone( T )` | Epetra vector or multi-vector |
| `ops_epetra_vector.cc` | `ops_epetra.vector_clone` | `Epetra_Vector` |
| `ops_epetra_multi_vector.cc` | `epetraMultiVectorGlobSize15Fixture.multi_vector_clone` | `Epetra_MultiVector` |

ops: epetra: revise `clone` overload constraints

---

include/pressio/ops/kokkos/ops_dot.hpp
tests/functional_small/ops/ops_kokkos_vector.cc

refs #524
Kokkos `dot` overloads:
| `void dot(a, b, scalar)`<br>`scalar dot(a, b)` | Kokkos rank-1 views or expressions | requires underlying scalar type<br>to be known integral of floating-point type |
| `ops_kokkos_vector.cc` | `ops_kokkos.vector_dot` | `Kokkos::View<double*>` |
| `ops_kokkos_diag.cc` | `ops_kokkos.diag_dot_diag`<br>`ops_kokkos.diag_dot_vector` | `pressio::diag( Kokkos::View<double**> )` |
| `ops_kokkos_span.cc` | `ops_kokkos.span_dot` | `pressio::span( Kokkos::View<double*> )` |

ops: kokkos: revise `dot`

---

include/pressio/ops.hpp
include/pressio/ops/tpetra_block/ops_scale.hpp
tests/functional_small/ops/ops_tpetra_block_multi_vector.cc
tests/functional_small/ops/ops_tpetra_block_vector.cc

refs #445
Block Tpetra overloads of `pressio::ops::scale`:
| `scale` | Tpetra block vector or block multi-vector | requires underlying scalar type to be known integral of floating-point type |
| `ops_tpetra_block_vector.cc` | `ops_tpetra_block.vector_scale` | `Tpetra::BlockVector<>` |
| `ops_tpetra_block_multi_vector.cc` | `tpetraBlockMultiVectorGlobSize15NVec3BlockSize4Fixture.multi_vector_scale` | `Tpetra::BlockMultiVector<>` |

 ops: tpetra-block: `scale` implementation and tests

---

include/pressio/ops/epetra/ops_dot.hpp

refs #524
Epetra `dot` overloads:
| `void dot(a, b, scalar)`<br>`scalar dot(a, b)` | `Epetra_Vector` | requires underlying scalar type<br>to be known integral of floating-point type |
| `ops_epetra_vector.cc` | `ops_epetra.vector_dot` | `Epetra_Vector` |

ops: epetra: revise `dot` overload constraints

---

include/pressio/ops/tpetra/ops_dot.hpp

refs #524
Tpetra `dot` overloads:
| `void dot(a, b, scalar)`<br>`scalar dot(a, b)` | Tpetra vectors | requires underlying scalar type<br>to be known integral of floating-point type |
| `ops_tpetra_vector.cc` | `ops_tpetra.vector_dot` | `Tpetra::Vector<>` |

ops: tpetra: revise `dot` overload constraints

---

include/pressio/ops/tpetra_block/ops_dot.hpp

refs #524
Block Tpetra `dot` overloads:
| `void dot(a, b, scalar)`<br>`scalar dot(a, b)` | Tpetra block vectors | requires underlying scalar type<br>to be known integral of floating-point type |
| `ops_tpetra_block_vector.cc` | `ops_tpetra_block.vector_dot` | `Tpetra::BlockVector<>` |

ops: tpetra-block: revise `dot` overload constraints

---

include/pressio/ops/tpetra/ops_deep_copy.hpp

refs #518
Tpetra `deep_copy` overloads:
|:---:|:---:|
| `deep_copy( T2 & dest, const T1 & src )` | Tpetra vectors or multi-vectors |
| `ops_tpetra_vector.cc` | `ops_tpetra.vector_deep_copy` | `Tpetra::Vector<>` |
| `ops_tpetra_multi_vector.cc` | `tpetraMultiVectorGlobSize15Fixture.multi_vector_deep_copy` | `Tpetra::MultiVector<>` |

ops: tpetra: revise `deep_copy` overload constraints

---

include/pressio/ops/tpetra_block/ops_deep_copy.hpp
tests/functional_small/ops/ops_tpetra_block_multi_vector.cc
tests/functional_small/ops/ops_tpetra_block_vector.cc

refs #518
Block Tpetra `deep_copy` overloads:
|:---:|:---:|
| `deep_copy( T2 & dest, const T1 & src )` | Tpetra block vectors or block multi-vectors |
| `ops_tpetra_block_vector.cc` | `ops_tpetra_block.vector_deep_copy` | `Tpetra::Vector<>` |
| `ops_tpetra_block_multi_vector.cc` | `tpetraBlockMultiVectorGlobSize15NVec3BlockSize4Fixture.multi_vector_deep_copy` | `Tpetra::MultiVector<>` |

ops: tpetra-block: revise `deep_copy`

---

include/pressio/ops/tpetra/ops_extent.hpp

refs #522
Tpetra `extent` overloads:
|:---:|:---:|
| `extent(const T & objectIn, const IndexType i)` | Tpetra vector |
| `extent(const T & objectIn, const IndexType i)` | Tpetra multi-vector |
| `ops_tpetra_vector.cc` | `ops_tpetra.vector_extent` | `Tpetra::Vector<>` |
| `ops_tpetra_multi_vector.cc` | `tpetraMultiVectorGlobSize15Fixture.multi_vector_extent` | `Tpetra::MultiVector<>` |

ops: tpetra: revise `extent` overload constraints

---

include/pressio/ops/epetra/ops_extent.hpp

refs #522
Epetra `extent` overloads:
|:---:|:---:|
| `extent(const T & objectIn, const IndexType i)` | `Epetra_Vector` |
| `extent(const T & objectIn, const IndexType i)` | `Epetra_MultiVector` |
| `ops_epetra_vector.cc` | `ops_epetra.vector_extent` | `Epetra_Vector` |
| `ops_epetra_multi_vector.cc` | `epetraMultiVectorGlobSize15Fixture.multi_vector_extent` | `Epetra_MultiVector` |

ops: epetra: revise `extent` overload constraints

---

include/pressio/ops/kokkos/ops_extent.hpp

refs #522
Kokkos `extent` overloads:
|:---:|:---:|
| `extent(const T & objectIn, const IndexType i)` | Kokkos view or expression |
| `ops_kokkos_vector.cc` | `ops_kokkos.vector_extent` | `Kokkos::View<double*>` |
| `ops_kokkos_diag.cc` | `ops_kokkos.diag_extent` | `pressio::diag( Kokkos::View<double**> )` |
| `ops_kokkos_span.cc` | `ops_kokkos.span_extent` | `pressio::span( Kokkos::View<double*> )` |
| `ops_kokkos_matrix.cc` | `ops_kokkos.dense_matrix_extent` | `Kokkos::View<double**>` |
| `ops_kokkos_subspan.cc` | `ops_kokkos.subspan_extent` | `pressio::subspan( Kokkos::View<double**> )` |

ops: kokkos: revise `extent` overload constraints

---

include/pressio/ops/eigen/ops_level2.hpp
include/pressio/ops/eigen/ops_rank1_update.hpp
include/pressio/ops/eigen/ops_rank2_update.hpp
include/pressio/ops/epetra/ops_level2.hpp
include/pressio/ops/epetra/ops_multi_vector_update.hpp
include/pressio/ops/epetra/ops_rank1_update.hpp
include/pressio/ops/kokkos/ops_level2.hpp
include/pressio/ops/tpetra/ops_level2.hpp

We no longer need anti-NaN-injection guards around `pressio::ops::scale()`, because it calls `pressio::ops::set_zero()` internally, if needed.
refs #445

ops: clean `scale` guards

---

include/pressio/expressions/impl/asdiagonalmatrix_classes.hpp
include/pressio/expressions/impl/diag_classes.hpp
include/pressio/expressions/impl/span_classes.hpp
include/pressio/expressions/impl/subspan_classes.hpp
include/pressio/ops/eigen/ops_extent.hpp
include/pressio/ops/epetra/ops_extent.hpp
include/pressio/ops/kokkos/ops_extent.hpp
include/pressio/ops/tpetra/ops_extent.hpp
include/pressio/ops/tpetra_block/ops_extent.hpp
tests/functional_small/ops/ops_eigen_diag.cc
tests/functional_small/ops/ops_eigen_matrix.cc
tests/functional_small/ops/ops_eigen_span.cc
tests/functional_small/ops/ops_eigen_subspan.cc
tests/functional_small/ops/ops_eigen_vector.cc
tests/functional_small/ops/ops_epetra_multi_vector.cc
tests/functional_small/ops/ops_epetra_vector.cc
tests/functional_small/ops/ops_kokkos_diag.cc
tests/functional_small/ops/ops_kokkos_matrix.cc
tests/functional_small/ops/ops_kokkos_span.cc
tests/functional_small/ops/ops_kokkos_subspan.cc
tests/functional_small/ops/ops_kokkos_vector.cc
tests/functional_small/ops/ops_tpetra_block_multi_vector.cc
tests/functional_small/ops/ops_tpetra_block_vector.cc
tests/functional_small/ops/ops_tpetra_multi_vector.cc
tests/functional_small/ops/ops_tpetra_vector.cc

Based on https://github.com/Pressio/pressio/pull/513#discussion_r1050558365 from @fnrizzi:
> it should not return 0 if i!=0 , because a vector has 1 column.
> 
> ```
>   return (i == 0) ? objectIn.length() : 1;
> ```
this PR makes `presssio::ops::extent()` consistently return 1 for over-the-rank extents and adds related unit tests for each TPL implementation.

ops: assume 1 for overranked extents

---

include/pressio/ops/eigen/ops_abs.hpp
tests/functional_small/ops/ops_eigen_span.cc

refs #516
Eigen `abs` overloads:
| function | parameter types | remarks |
| `abs(T1 & y, const T2 & x)` | Eigen native vectors or rank-1 expressions | requires underlying scalar type<br>to be known integral of floating-point type |
| `ops_eigen_vector.cc` | `ops_eigen.vector_abs` | `Eigen::VectorXd` |
| `ops_eigen_diag.cc` | `ops_eigen.diag_abs` | `pressio::diag( Eigen::MatrixXd )` |
| `ops_eigen_span.cc` | `ops_eigen.span_abs` | `pressio::span( Eigen::VectorXd )` |

ops: eigen: revise `abs`

---

include/pressio/ops/eigen/ops_elementwise_multiply.hpp

refs #523
Eigen `elementwise_multiply` has one overload which requires the underlying scalar type to be the same for `T`, `T1` and `T2` and to be known integral of floating-point type:
```cpp
elementwise_multiply(const alpha_t & alpha, const T & x, const T1 & z, const beta_t & beta, T2 & y)
```
| type name | requirements |
|:---:|:---|
| `T`, `T1`, `T2` | ● each can be Eigen native vector or rank-1 expression<br>● all must have same underlying scalar type |
| `alpha_t`, `beta_t` | must be convertible to the scalar type |
| `ops_eigen_vector.cc` | `ops_eigen.vector_elementwiseMultiply` | `Eigen::VectorXd` |
| `ops_eigen_diag.cc` | `ops_eigen.diag_elementwiseMultiply` | `pressio::diag( …

ops: eigen: revise `elementwise_multiply`

---

include/pressio/ops/kokkos/ops_elementwise_multiply.hpp

refs #523
Kokkos `elementwise_multiply` has one overload which requires the underlying scalar type to be the same for `T`, `T1` and `T2` and to be known integral of floating-point type:
```cpp
elementwise_multiply(const alpha_t & alpha, const T & x, const T1 & z, const beta_t & beta, T2 & y)
```
| type name | requirements |
|:---:|:---|
| `T`, `T1`, `T2` | ● each can be native Kokkos view or rank-1 expression<br>● all must have same underlying scalar type |
| `alpha_t`, `beta_t` | must be convertible to the scalar type |
| `ops_kokkos_vector.cc` | `ops_kokkos.vector_elementwiseMultiply` | `Kokkos::View<double*>` |
| `ops_kokkos_diag.cc` | `ops_kokkos.diag_elementwiseMultiply` | …

ops: kokkos: revise `elementwise_multiply`

---

include/pressio/ops/tpetra_block/ops_elementwise_multiply.hpp

refs #523
Block Tpetra `elementwise_multiply` has one overload which requires the underlying scalar type to be the same for `T`, `T1` and `T2` and to be known integral of floating-point type:
```cpp
elementwise_multiply(const alpha_t & alpha, const T & x, const T1 & z, const beta_t & beta, T2 & y)
```
| type name | requirements |
|:---:|:---|
| `T`, `T1`, `T2` | ● each must be Tpetra block vector <br>● all must have the same underlying scalar type |
| `alpha_t`, `beta_t` | must be convertible to the scalar type |
| `ops_tpetra_block_vector.cc` | `ops_tpetra_block.vector_elementwiseMultiply` | `Tpetra::BlockVector<>` |

ops: tpetra-block: revise `elementwise_multiply`

---

include/pressio/ops/tpetra/ops_abs.hpp

refs #516
Tpetra `abs` overloads:
|:---:|:---:|
| `abs(T1 & y, const T2 & x)` | Tpetra vector |
| `ops_tpetra_vector.cc` | `ops_tpetra.vector_abs` | `Tpetra::Vector<>` |

ops: tpetra: revise `abs`

---

include/pressio/ops/tpetra_block/ops_abs.hpp

refs #516
Block Tpetra `abs` overloads:
|:---:|:---:|
| `abs(T1 & y, const T2 & x)` | Tpetra block vector |
| `ops_tpetra_block_vector.cc` | `ops_tpetra_block.vector_abs` | `Tpetra::BlockVector<>` |

ops: tpetra-block: revise `abs`

---

.github/workflows/ci-workflow.yml

Solution for issue #617 part 1/2.
Remove `pressio-builder` and replace it with the pure `cmake` command.

#617 CI workflows: `CI` job, get rid of pressio-builder

---

include/pressio/rom/impl/linear_trial_column_subspace.hpp
tests/functional_small/rom/trial_subspace_stdvec_full_state_eigen_reduced_state.cc

this is to ensure that any shift vector passed to trial space is set to zero if the trial space is non affine. 
otherwise, if one passes a temporary vec that could have all sort of weird initializations leading to problems when used

set shift to zero if non affine is selected

---

.github/workflows/ci-docker.yml
.github/workflows/ci-trilinos.yml
docker_scripts/ubuntu-gnu-trilinos.dockerfile

Add another set of CI jobs using [Trilinos 14.4.0](https://github.com/trilinos/Trilinos/releases/tag/trilinos-release-14-4-0).
Note: add that and leave existing builds (using Trilinos `ef73d14`) too.

add Trilinos 14.4.0 image and build

---

include/pressio/rom/impl/lspg_unsteady_problem.hpp

this is not the proper fix. The proper fix is to move what we can move, similarly to what we do for galerkin.
But doing so will require fixing the move semantics for good everywhere by actually thinking about it properly!

use owing ptr, fixes usecase for schwarz

---

include/pressio/ops/eigen/ops_deep_copy.hpp
tests/functional_small/ops/ops_eigen_diag.cc
tests/functional_small/ops/ops_eigen_matrix.cc
tests/functional_small/ops/ops_eigen_span.cc
tests/functional_small/ops/ops_eigen_subspan.cc
tests/functional_small/ops/ops_eigen_vector.cc

refs #518
Eigen `deep_copy` overloads:
| function | input |
|:---:|:---:|
| `deep_copy( T2 & dest, const T1 & src )` | native Eigen containers or Eigen expressions |
| `ops_eigen_vector.cc` | `ops_eigen.vector_deep_copy` | `Eigen::VectorXd` |
| `ops_eigen_diag.cc` | `ops_eigen.diag_deep_copy` | `pressio::diag( Eigen::MatrixXd )` copied to the same and to `Eigen::VectorXd` |
| `ops_eigen_span.cc` | `ops_eigen.span_deep_copy` | `pressio::span( Eigen::VectorXd )` copied to the same and to `Eigen::VectorXd` |
| `ops_eigen_matrix.cc` | `ops_eigen.dense_matrix_deep_copy` | `Eigen::MatrixXd` |
| `ops_eigen_subspan.cc` | `ops_eigen.subspan_deep_copy` | `pressio::subspan( Eigen::MatrixXd )` …

ops: eigen: revise `deep_copy`

---

include/pressio/ops/kokkos/ops_deep_copy.hpp
tests/functional_small/ops/ops_kokkos_diag.cc
tests/functional_small/ops/ops_kokkos_span.cc
tests/functional_small/ops/ops_kokkos_subspan.cc

refs #518
Kokkos `deep_copy` overloads:
|:---:|:---:|
| `deep_copy( T2 & dest, const T1 & src )` | Kokkos views or expressions |
| `ops_kokkos_vector.cc` | `ops_kokkos.vector_deep_copy` | `Kokkos::View<double*>` |
| `ops_kokkos_diag.cc` | `ops_kokkos.diag_deep_copy` | `pressio::diag( Kokkos::View<double**> )` |
| `ops_kokkos_span.cc` | `ops_kokkos.span_deep_copy` | `pressio::span( Kokkos::View<double*> )` |
| `ops_kokkos_matrix.cc` | `ops_kokkos.dense_matrix_deep_copy` | `Kokkos::View<double**>` |
| `ops_kokkos_subspan.cc` | `ops_kokkos.subspan_deep_copy` | `pressio::subspan( Kokkos::View<double**> )` |

ops: kokkos: revise `deep_copy`

---

include/pressio/mpl/mpl_ConfigDefs.hpp
include/pressio/ode/impl/ode_explicit_stepper_with_mass_matrix.hpp
include/pressio/ode/impl/ode_explicit_stepper_without_mass_matrix.hpp
include/pressio/ode/impl/ode_implicit_policy_residual_jacobian_with_mass_matrix.hpp
include/pressio/ode/impl/ode_implicit_policy_residual_jacobian_without_mass_matrix.hpp
include/pressio/ode/impl/ode_implicit_stepper_arbitrary.hpp
include/pressio/ode/impl/ode_implicit_stepper_standard.hpp
include/pressio/solvers_nonlinear/impl/diagnostics.hpp
include/pressio/solvers_nonlinear/impl/instance_or_reference_wrapper.hpp
include/pressio/solvers_nonlinear/impl/registries.hpp
include/pressio/utils.hpp
tests/functional_small/ode_advancers/to_target_time_with_time_step_recovery.cc
tests/functional_small/solvers_nonlinear/gaussnewton_normaleqs_problem3_eigen.cc
tests/functional_small/solvers_nonlinear/gaussnewton_normaleqs_problem5_eigen.cc
tests/functional_small/solvers_nonlinear/gaussnewton_normaleqs_problem9_eigen.cc
tests/functional_small/solvers_nonlinear/gaussnewton_qr_problem3_eigen.cc
tests/functional_small/solvers_nonlinear/gaussnewton_qr_problem8_eigen.cc
tests/functional_small/solvers_nonlinear/levmar_normaleqs_problem9_eigen.cc
tests/functional_small/solvers_nonlinear/weighted_gaussnewton_normaleqs_problem3_eigen.cc

#688: Move utils_instance_or_reference_wrapper.hpp to `solvers_nonlinear`

---

include/pressio/solvers_nonlinear/impl/updaters.hpp

forgot to use zeta in https://github.com/Pressio/pressio/pull/705

actually use zeta  in BacktrackStrictlyDecreasingObjectiveUpdater

---

.github/workflows/ci-trilinos.yml
CMakeLists.txt

CI will pass once [pressio-ops PR 32](https://github.com/Pressio/pressio-ops/pull/32) is merged (see [this commit](https://github.com/Pressio/pressio/pull/713/commits/c052d5b26517c7326f23f9ea015ec5957595c25b), where I targeted the updated pressio-ops branch instead of `develop`)

Update trilinos container tags

---

.github/workflows/ci-kokkos.yml
tests/cmake/options.cmake
tests/functional_small/solvers_linear/CMakeLists.txt

#707: create a kokkos-only pipeline

---

docs/source/concepts_note.rst
docs/source/conf.py
docs/source/configuration.rst
docs/source/index.rst
include/pressio/pressio_macros.hpp
tests/cmake/version.cmake

Fixes #726 
This PR:
- Adds `PRESSIO_*_VERSION` macros to the pressio library (Instead of using the versions defined in `pressio-ops`)
- Fixes the version of Pressio in the documentation
- Updates the versions of TPLs in the documentation to reflect current CI
- Other drive-by fixes in the documentation

#726: Clean up docs and version
