- .travis.yml
> Fix travis to run unit tests

- packages/pressio_rom.hpp
- packages/rom/src/wls/apis/rom_wls_hessian_gradient_system_api_impl.hpp
- packages/rom/src/wls/policies/rom_wls_hessian_and_gradient_sequential_policy_impl.hpp
- packages/rom/src/wls/policies/rom_wls_jacobians_container.hpp
- packages/rom/src/wls/policies/rom_wls_jacobians_container_impl.hpp
- packages/rom/src/wls/time_schemes/rom_wls_bdf2.hpp
- packages/rom/src/wls/time_schemes/rom_wls_implicit_euler.hpp
- tests/rom/burgers1d/wls/wls_burgers_driver_mpi.hpp
- tests/rom/burgers1d/wls/wls_burgers_driver_serial.hpp
Merge request for frozen Jacobians feature branch.
> Wls frozen jacobians

- packages/apps/src/burgers1d/apps_burgers1d_eigen_residual_api.hpp
- packages/pressio_rom.hpp
- packages/rom/src/meta/wls_residual_api/rom_model_meets_residual_api_for_wls.hpp
- packages/rom/src/meta/wls_velocity_api/rom_model_meets_velocity_api_for_wls.hpp
- packages/rom/src/wls/apis/rom_wls_hessian_gradient_system_api_impl.hpp
- packages/rom/src/wls/policies/rom_wls_hessian_and_gradient_sequential_policy_impl.hpp
- packages/rom/src/wls/time_schemes/rom_wls_bdf2.hpp
- packages/rom/src/wls/time_schemes/rom_wls_implicit_euler.hpp
- packages/rom/src/wls/time_schemes/rom_wls_select_timescheme_helper.hpp
- tests/rom/burgers1d/eigen/wls_normal_eq_velocity_api_eigen_rom/main.cc
- tests/rom/burgers1d/wls/burgers_fom_functions_eigen.hpp
- tests/rom/burgers1d/wls/wls_burgers_driver_mpi.hpp
- tests/rom/burgers1d/wls/wls_burgers_driver_serial.hpp
Slightly reorganized version of WLS with residual API
> Wls reorganize

- .github/workflows/ghactions.yml
The feature aims to add a CI using GitHub Actions script
> Ci gh actions rc

- .github/workflows/ghactions.yml
This PR aims to provide the new Trilinos build that uses the docker dedicated to the TPL build.
> Improve gh actions for trilinos final

- .github/workflows/ghactions.yml
- README.md
@fnrizzi 
This PR aims to :  
- Fix the badge link contained by the README 
- Removed from the coverage report the package/utils/logger which contains TPL code
> 241 update code coverage

- .github/workflows/ghactions.yml
> HOTFIX: run apt-get update

- .github/workflows/cancelling.yml
- .github/workflows/pressio_testing.yml
- docker_scripts/fedora-34-clang_12-eigen_3.3.7-gtest-trilinos_9fec35276d846a667bc668ff4cbdfd8be0dfea08.dockerfile
- docker_scripts/fedora-34-clang_12-eigen_3.3.7-gtest.dockerfile
- docker_scripts/fedora-34-clang_12-gtest.dockerfile
- docker_scripts/fedora-34-clang_12.dockerfile
- docker_scripts/fedora-34-gnu_11-eigen_3.3.7-gtest-trilinos_9fec35276d846a667bc668ff4cbdfd8be0dfea08.dockerfile
- docker_scripts/fedora-34-gnu_11-eigen_3.3.7-gtest.dockerfile
- docker_scripts/fedora-34-gnu_11-gtest.dockerfile
- docker_scripts/fedora-34-gnu_11.dockerfile
- docker_scripts/ubuntu-20.04-clang_9-eigen_3.3.7-gtest-trilinos_9fec35276d846a667bc668ff4cbdfd8be0dfea08.dockerfile
- docker_scripts/ubuntu-20.04-clang_9-eigen_3.3.7-gtest.dockerfile
- docker_scripts/ubuntu-20.04-clang_9-gtest.dockerfile
- docker_scripts/ubuntu-20.04-clang_9.dockerfile
- docker_scripts/ubuntu-20.04-gnu_9-eigen_3.3.7-gtest-trilinos_9fec35276d846a667bc668ff4cbdfd8be0dfea08.dockerfile
- docker_scripts/ubuntu-20.04-gnu_9-eigen_3.3.7-gtest.dockerfile
- docker_scripts/ubuntu-20.04-gnu_9-gtest.dockerfile
- docker_scripts/ubuntu-20.04-gnu_9.dockerfile
- docker_scripts/ubuntu-20.04-intel-eigen_3.3.7-gtest-trilinos_9fec35276d846a667bc668ff4cbdfd8be0dfea08.dockerfile
- docker_scripts/ubuntu-20.04-intel-eigen_3.3.7-gtest.dockerfile
- docker_scripts/ubuntu-20.04-intel-gtest.dockerfile
- docker_scripts/ubuntu-20.04-intel.dockerfile
- added dockerfiles
- built docker images
- sent docker images to the dockerhub repository
- started CI cancelling action
- added testing for current script with usage of created docker images
> Ci improvements docker images

- docker_scripts/ubuntu-20.04-gnu_10-eigen_3.3.7-gtest-trilinos_hash-ef73d14babf6e7556b0420add98cce257ccaa56b.dockerfile
- checked if numpy works from inside container
> #350: - added python3-numpy package

- include/pressio/ops/eigen/ops_fill.hpp
- include/pressio/ops/epetra/ops_fill.hpp
- include/pressio/ops/kokkos/ops_fill.hpp
- include/pressio/ops/tpetra/ops_fill.hpp
- include/pressio/ops/tpetra_block/ops_fill.hpp
> ops: fill() review

- docs/source/components/ops/fill.rst
> docs: ops: revise `fill()`

- include/pressio/ops/eigen/ops_fill.hpp
- include/pressio/ops/epetra/ops_fill.hpp
- include/pressio/ops/tpetra/ops_fill.hpp
- include/pressio/ops/tpetra_block/ops_fill.hpp
- fix parens and remove concept since we decided not use those for ops yet
> complete #481

- include/pressio/ops/eigen/ops_level2.hpp
- tests/functional_small/ops/ops_eigen_level2.cc
> ops: revise eigen matrix-vector product

- include/pressio/ops/kokkos/ops_level2.hpp
- tests/functional_small/ops/ops_kokkos_level2.cc
> ops: revise kokkos matrix-vector product

- docs/source/components/rom_concepts.rst
- docs/source/components/rom_concepts_foms/semidiscrete_fom_with_jac_mm_action.rst
- docs/source/components/rom_concepts_implicit_galerkin/default_mm.rst
- docs/source/components/rom_galerkin_unsteady_implicit.rst
- include/pressio/rom/concepts/fom_semi_discrete_with_jac_and_mm_action.hpp
- include/pressio/rom/concepts/galerkin_implicit_default_with_varying_mm.hpp
- include/pressio/rom/galerkin_unsteady_implicit.hpp
- include/pressio/rom/impl/galerkin_unsteady_system_default_rhs_and_jacobian_and_mm.hpp
- include/pressio/rom/reduced_operators_traits.hpp
- include/pressio/rom_concepts.hpp
- tests/functional_small/rom/galerkin_unsteady_implicit/CMakeLists.txt
- tests/functional_small/rom/galerkin_unsteady_implicit/main6.cc
related to https://github.com/Pressio/pressio/issues/382
- note that test is still incomplete
> galerkin unsteady implicit default with varying mass matrix

- include/pressio/ops/tpetra/ops_level2.hpp
- tests/functional_small/ops/fixtures/tpetra_only_fixtures.hpp
- tests/functional_small/ops/ops_kokkos_level2.cc
- tests/functional_small/ops/ops_shared_level2.hpp
- tests/functional_small/ops/ops_tpetra_level2.cc
- tests/functional_small/ops/ops_tpetra_multi_vector.cc
> ops: revise tpetra matrix-vector product

- include/pressio/ops/tpetra_block/ops_level2.hpp
- tests/functional_small/ops/fixtures/tpetra_block_only_fixtures.hpp
- tests/functional_small/ops/ops_tpetra_block_level2.cc
- tests/functional_small/ops/ops_tpetra_block_multi_vector.cc
> ops: revise tpetra block matrix-vector product

- include/pressio/ops.hpp
- include/pressio/ops/epetra/ops_level2.hpp
- include/pressio/ops/epetra/ops_scale.hpp
- tests/functional_small/ops/fixtures/epetra_only_fixtures.hpp
- tests/functional_small/ops/ops_epetra_level2.cc
- tests/functional_small/ops/ops_epetra_multi_vector.cc
> ops: revise epetra matrix-vector product

- include/pressio/ops/eigen/ops_rank1_update.hpp
- tests/functional_small/ops/ops_eigen_vector.cc
> ops: eigen: revise rank-1 update

- include/pressio/ops/tpetra/ops_rank1_update.hpp
- tests/functional_small/ops/ops_tpetra_vector.cc
>  ops: tpetra: revise rank-1 update

- include/pressio/ops/eigen/ops_rank2_update.hpp
- tests/functional_small/ops/ops_eigen_matrix.cc
> ops: eigen: revise rank-2 `update`

- include/pressio/ops/eigen/ops_min_max.hpp
- tests/functional_small/ops/ops_eigen_matrix.cc
- tests/functional_small/ops/ops_eigen_subspan.cc
> ops: eigen: revise `min`/`max`

- include/pressio/ops/eigen/ops_dot.hpp
refs #524
Eigen `dot` overloads:
| `void dot(a, b, scalar)`<br>`scalar dot(a, b)` | Eigen vectors or rank-1 expressions | requires underlying scalar type<br>to be known integral of floating-point type |
| `ops_eigen_vector.cc` | `ops_eigen.vector_dot` | `Eigen::VectorXd` |
| `ops_eigen_diag.cc` | `ops_eigen.diag_dot_diag`<br>`ops_eigen.diag_dot_vector` | `pressio::diag( Eigen::MatrixXd )` |
| `ops_eigen_span.cc` | `ops_eigen.span_dot` | `pressio::span( Eigen::VectorXd )` |
> ops: eigen: revise `dot` overload constraints

- docs/source/conf.py
Addition of a function in the `conf.py` file.
Use this function to obtain the Pressio version written in the `version.txt` file.
> Update versioning in conf.py

- include/pressio/pressio_cmake_config.h.in
remove things we don't really use
> cleanup cmake_config

- docs/source/installation.rst
Corrects a typo in the documentation.
> Fix typing error

- .github/workflows/ci-baseline.yml
- .github/workflows/ci-trilinos.yml
- tests/cmake/options.cmake
- tests/functional_small/ode_steppers/ode_forward_euler_custom_ind_var_type_eigen.cc
@cz4rs can you please help me out with this? 
I like to add the Wall Werror flags to the CI, but need to find a way to limit the flags to pressio only (if the TPL triggers things with this, not our fault). so that the CI fails for these only if they occur due to pressio
> add `-Wall -Werror`

- .github/workflows/ci-docker.yml
- .github/workflows/ci-trilinos.yml
- docker_scripts/README.md
> #650: add new trilinos pipeline for CI and step-by-step guide for how to add a new one

- include/pressio/rom/galerkin_unsteady_implicit.hpp
- include/pressio/rom/impl/galerkin_unsteady_system_hypred_fully_discrete_fom.hpp
this was missing in develop , something got out of sync
> add missing overload and fix impl

- include/pressio/solvers_nonlinear/impl/nonlinear_least_squares.hpp
> #693: remove redundant `if`

- .github/workflows/ci-baseline.yml
- .github/workflows/ci-kokkos.yml
- .github/workflows/ci-trilinos.yml
> #720: Update container names in CI

- .github/workflows/ci-baseline.yml
- .github/workflows/ci-kokkos.yml
- .github/workflows/ci-trilinos.yml
> #728: Update CI to use new containers

- .github/workflows/deploy_docs.yml
> #739: Fix documentation pipeline after renaming repository

- include/pressio/pressio_macros.hpp
- version.txt
> #781: Bump version number to 0.17.0
